apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: messagelistener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thegym
      component: messagelistener
      version: 0.0.1  
  serviceName: "messagelistener"
  template:
    metadata:
      name: messagelistener
      labels:
        app: thegym
        component: messagelistener
        version: 0.0.1  
    spec:
      containers:
      - name: messagelistener
        image: digitalemil/thesimplegym:microservice-messagelistener-v0.0.1
        imagePullPolicy: Always
        env:
        - name: APPDEF
          value: "{'name':'The Gym','showLocation':'true','fields':[{'name':'heartrate','pivot':'true','type':'Integer'},{'name':'user','pivot':false,'type':'String'},{'name':'deviceid','pivot':false,'type':'String'},{'name':'color','pivot':false,'type':'String'},{'name':'id','pivot':'false','type':'Long'},{'name':'location','pivot':'false','type':'Location'},{'name':'event_timestamp','pivot':'false','type':'Date/time'}],'transformer':'%0A%09result%3D%20rawtext%3B%0A%09%09%09%09%09%0A%09%09%09%09%09','topic':'hr','table':'hr','keyspace':'thegym','path':'thegym','creator':'','dockerrepo':'','img':'','vis':'','dash':'','hideloader':'true'}"
        - name: MESSAGE_TRANSFORMER
          value: http://messagetransformer
        - name: MESSAGE_VALIDATOR
          value: http://messagevalidator
        - name: PMML_EVALUATOR
          value: http://pmmlevaluator 
        - name: DOMAIN
          value: messagelistener:8081
        - name: PORT
          value: "8081"
        ports:
        - containerPort: 8081
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: messagelistener
spec:
  selector:
    app: thegym
    component: messagelistener
    version: 0.0.1    
  clusterIP: None
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 8081 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thegym
      component: ui
      version: 0.0.1     
  template:
    metadata:
      name: ui
      labels:
        app: thegym
        component: ui
        version: 0.0.1   
    spec:
      containers:
      - name: ui
        image: digitalemil/thesimplegym:microservice-ui-v0.0.1
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "80"
        - name: APPDEF
          value: "{'name':'The Gym','showLocation':'true','fields':[{'name':'heartrate','pivot':'true','type':'Integer'},{'name':'user','pivot':false,'type':'String'},{'name':'deviceid','pivot':false,'type':'String'},{'name':'color','pivot':false,'type':'String'},{'name':'id','pivot':'false','type':'Long'},{'name':'location','pivot':'false','type':'Location'},{'name':'event_timestamp','pivot':'false','type':'Date/time'}],'transformer':'%0A%09result%3D%20rawtext%3B%0A%09%09%09%09%09%0A%09%09%09%09%09','topic':'hr','table':'hr','keyspace':'thegym','path':'thegym','creator':'','dockerrepo':'','img':'','vis':'','dash':'','hideloader':'true'}"
        - name: LISTENER
          value: messagelistener
        - name: DOMAIN
          value: messagelistener:8081
        - name: APPDIR
          value: /opt/app
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: ui
spec:
  selector:
    app: thegym
    component: ui
    version: 0.0.1  
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagetransformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thegym
      component: messagetransformer
      version: 0.0.1    
  template:
    metadata:
      name: messagetransformer
      labels:
        app: thegym
        component: messagetransformer
        version: 0.0.1      
    spec:
      containers:
      - name: messagetransformer
        image: digitalemil/thesimplegym:microservice-messagetransformer-v0.0.1
        imagePullPolicy: Always
        env:
        - name: APPDEF
          value: "{'name':'The Gym','showLocation':'true','fields':[{'name':'heartrate','pivot':'true','type':'Integer'},{'name':'user','pivot':false,'type':'String'},{'name':'deviceid','pivot':false,'type':'String'},{'name':'color','pivot':false,'type':'String'},{'name':'id','pivot':'false','type':'Long'},{'name':'location','pivot':'false','type':'Location'},{'name':'event_timestamp','pivot':'false','type':'Date/time'}],'transformer':'%0A%09result%3D%20rawtext%3B%0A%09%09%09%09%09%0A%09%09%09%09%09','topic':'hr','table':'hr','keyspace':'thegym','path':'thegym','creator':'','dockerrepo':'','img':'','vis':'','dash':'','hideloader':'true'}"
        - name: PORT
          value: "8082"
        ports:
        - containerPort: 8082
---
kind: Service
apiVersion: v1
metadata:
  name: messagetransformer
spec:
  selector:
    app: thegym
    component: messagetransformer
    version: 0.0.1    
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagevalidator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thegym
      component: messagevalidator
      version: 0.0.1  
  template:
    metadata:
      name: messagevalidator
      labels:
        app: thegym
        component: messagevalidator
        version: 0.0.1   
    spec:
      containers:
      - name: messagevalidator
        image: digitalemil/thesimplegym:microservice-messagevalidator-v0.0.1
        imagePullPolicy: Always
        env:
        - name: APPDEF
          value: "{'name':'The Gym','showLocation':'true','fields':[{'name':'heartrate','pivot':'true','type':'Integer'},{'name':'user','pivot':false,'type':'String'},{'name':'deviceid','pivot':false,'type':'String'},{'name':'color','pivot':false,'type':'String'},{'name':'id','pivot':'false','type':'Long'},{'name':'location','pivot':'false','type':'Location'},{'name':'event_timestamp','pivot':'false','type':'Date/time'}],'transformer':'%0A%09result%3D%20rawtext%3B%0A%09%09%09%09%09%0A%09%09%09%09%09','topic':'hr','table':'hr','keyspace':'thegym','path':'thegym','creator':'','dockerrepo':'','img':'','vis':'','dash':'','hideloader':'true'}"
        - name: PORT
          value: "8083"
        ports:
        - containerPort: 8083
---
kind: Service
apiVersion: v1
metadata:
  name: messagevalidator
spec:
  selector:
    app: thegym
    component: messagevalidator
    version: 0.0.1    
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmmlevaluator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thegym
      component: pmmlevaluator
      version: 0.0.1  
  template:
    metadata:
      name: loader
      labels:
        app: thegym
        component: pmmlevaluator
        version: 0.0.1  
    spec:
      containers:
      - name: pmmlevaluator
        image: digitalemil/thesimplegym:microservice-pmmlevaluator-v0.0.1
        imagePullPolicy: Always
        env:
        - name: APPDEF
          value: "{'name':'The Gym','showLocation':'true','fields':[{'name':'heartrate','pivot':'true','type':'Integer'},{'name':'user','pivot':false,'type':'String'},{'name':'deviceid','pivot':false,'type':'String'},{'name':'color','pivot':false,'type':'String'},{'name':'id','pivot':'false','type':'Long'},{'name':'location','pivot':'false','type':'Location'},{'name':'event_timestamp','pivot':'false','type':'Date/time'}],'transformer':'%0A%09result%3D%20rawtext%3B%0A%09%09%09%09%09%0A%09%09%09%09%09','topic':'hr','table':'hr','keyspace':'thegym','path':'thegym','creator':'','dockerrepo':'','img':'','vis':'','dash':'','hideloader':'true'}"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: pmmlevaluator
spec:
  selector:
    app: thegym
    component: pmmlevaluator
    version: 0.0.1    
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thegym
      component: messageloader
      version: 0.0.1  
  template:
    metadata:
      name: loader
      labels:
        app: thegym
        component: messageloader
        version: 0.0.1  
    spec:
      containers:
      - name: loader
        image: digitalemil/thesimplegym:microservice-loadgenerator-v0.0.1
        imagePullPolicy: Always
        env:
        - name: APPDEF
          value: "{'name':'The Gym','showLocation':'true','fields':[{'name':'heartrate','pivot':'true','type':'Integer'},{'name':'user','pivot':false,'type':'String'},{'name':'deviceid','pivot':false,'type':'String'},{'name':'color','pivot':false,'type':'String'},{'name':'id','pivot':'false','type':'Long'},{'name':'location','pivot':'false','type':'Location'},{'name':'event_timestamp','pivot':'false','type':'Date/time'}],'transformer':'%0A%09result%3D%20rawtext%3B%0A%09%09%09%09%09%0A%09%09%09%09%09','topic':'hr','table':'hr','keyspace':'thegym','path':'thegym','creator':'','dockerrepo':'','img':'','vis':'','dash':'','hideloader':'true'}"
        - name: LISTENER
          value: http://messagelistener:8081
        - name: APPDIR
          value: /opt/app
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: messageloader
spec:
  selector:
    app: thegym
    component: messageloader
    version: 0.0.1    
  clusterIP: None
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80 
